class AppCountries {
  AppCountries._();

  static const List<String> all = [
    'India',
    'United States',
    'United Kingdom',
    'Australia',
    'Canada',
    'Germany',
    'France',
    'Japan',
    'China',
    'Brazil',
    'South Africa',
    'New Zealand',
    'Singapore',
    'Malaysia',
    'United Arab Emirates',
    'Saudi Arabia',
    'Kuwait',
    'Qatar',
    'Bahrain',
    'Oman',
    'Nepal',
    'Sri Lanka',
    'Bangladesh',
    'Pakistan',
    'Maldives',
    'Myanmar',
    'Thailand',
    'Indonesia',
    'Philippines',
    'Vietnam',
    'South Korea',
    'Hong Kong',
    'Taiwan',
    'Russia',
    'Italy',
    'Spain',
    'Netherlands',
    'Switzerland',
    'Sweden',
    'Norway',
    'Denmark',
    'Finland',
    'Belgium',
    'Austria',
    'Poland',
    'Mexico',
    'Argentina',
    'Chile',
    'Colombia',
    'Kenya',
    'Nigeria',
    'Ghana',
    'Egypt',
    'Israel',
    'Turkey',
    'Greece',
    'Portugal',
    'Czech Republic',
    'Hungary',
    'Ireland',
    'Mauritius',
    'Fiji',
    'Trinidad and Tobago',
    'Guyana',
    'Suriname',
    'Malaysia',
    'Cambodia',
    'Laos',
    'Mongolia',
    'Afghanistan',
    'Iran',
    'Iraq',
    'Jordan',
    'Lebanon',
    'Syria',
    'Yemen',
    'Ethiopia',
    'Tanzania',
    'Uganda',
    'Zimbabwe',
    'Zambia',
    'Mozambique',
  ];
}
