class AppCountries {
  AppCountries._();

  static const List<String> all = [
    'India',
    'United States',
    'United Kingdom',
    'Australia',
    'Canada',
    'Germany',
    'France',
    'Japan',
    'China',
    'Brazil',
    'South Africa',
    'New Zealand',
    'Singapore',
    'Malaysia',
    'United Arab Emirates',
    'Saudi Arabia',
    'Kuwait',
    'Qatar',
    'Bahrain',
    'Oman',
    'Nepal',
    'Sri Lanka',
    'Bangladesh',
    'Pakistan',
    'Maldives',
    'Myanmar',
    'Thailand',
    'Indonesia',
    'Philippines',
    'Vietnam',
    'South Korea',
    'Hong Kong',
    'Taiwan',
    'Russia',
    'Italy',
    'Spain',
    'Netherlands',
    'Switzerland',
    'Sweden',
    'Norway',
    'Denmark',
    'Finland',
    'Belgium',
    'Austria',
    'Poland',
    'Mexico',
    'Argentina',
    'Chile',
    'Colombia',
    'Kenya',
    'Nigeria',
    'Ghana',
    'Egypt',
    'Israel',
    'Turkey',
    'Greece',
    'Portugal',
    'Czech Republic',
    'Hungary',
    'Ireland',
    'Mauritius',
    'Fiji',
    'Trinidad and Tobago',
    'Guyana',
    'Suriname',
    'Malaysia',
    'Cambodia',
    'Laos',
    'Mongolia',
    'Afghanistan',
    'Iran',
    'Iraq',
    'Jordan',
    'Lebanon',
    'Syria',
    'Yemen',
    'Ethiopia',
    'Tanzania',
    'Uganda',
    'Zimbabwe',
    'Zambia',
    'Mozambique',
  ];

  static const List<String> indianCities = [
    'Mumbai', 'Delhi', 'Bengaluru', 'Hyderabad', 'Ahmedabad', 'Chennai',
    'Kolkata', 'Pune', 'Jaipur', 'Surat', 'Lucknow', 'Kanpur', 'Nagpur',
    'Indore', 'Thane', 'Bhopal', 'Visakhapatnam', 'Pimpri-Chinchwad',
    'Patna', 'Vadodara', 'Ghaziabad', 'Ludhiana', 'Agra', 'Nashik',
    'Faridabad', 'Meerut', 'Rajkot', 'Varanasi', 'Srinagar', 'Aurangabad',
    'Dhanbad', 'Amritsar', 'Navi Mumbai', 'Allahabad', 'Ranchi', 'Howrah',
    'Coimbatore', 'Jabalpur', 'Gwalior', 'Vijayawada', 'Jodhpur', 'Madurai',
    'Raipur', 'Kota', 'Guwahati', 'Chandigarh', 'Solapur', 'Hubli',
    'Tiruchirappalli', 'Bareilly', 'Mysore', 'Tiruppur', 'Gurgaon', 'Aligarh',
    'Jalandhar', 'Bhubaneswar', 'Salem', 'Mira-Bhayandar', 'Warangal',
    'Guntur', 'Bhiwandi', 'Saharanpur', 'Gorakhpur', 'Bikaner', 'Amravati',
    'Noida', 'Jamshedpur', 'Bhilai', 'Cuttack', 'Firozabad', 'Kochi',
    'Bhavnagar', 'Dehradun', 'Durgapur', 'Asansol', 'Nanded', 'Kolhapur',
    'Ajmer', 'Latur', 'Udaipur', 'Siliguri', 'Jhansi', 'Ulhasnagar',
    'Jammu', 'Sangli', 'Mangalore', 'Erode', 'Belgaum', 'Ambattur',
    'Tirunelveli', 'Malegaon', 'Gaya', 'Jalgaon', 'Maheshtala', 'Shimla',
    'Trimbak', 'Trimbakeshwar',
  ];
}
